---
# File: cni_plugin.yml - package installation tasks for Nomad CNI Plugin

- name: Create cni directory
  ansible.builtin.file:
    dest: "{{ nomad_cni_dir }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0750"

- name: Download Nomad CNI
  ansible.builtin.get_url:
    url: "{{ nomad_cni_zip_url }}"
    dest: "{{ role_path }}/files/{{ nomad_cni_pkg }}"
    mode: "0640"
    checksum: "sha256:{{ nomad_cni_checksum_file_url }}"
    timeout: "42"
  become: false
  tags: installation
  delegate_to: 127.0.0.1

- name: Download Nomad consul-cni
  ansible.builtin.get_url:
    url: "{{ nomad_consul_cni_zip_url }}"
    dest: "{{ role_path }}/files/{{ nomad_consul_cni_pkg }}"
    mode: "0640"
    checksum: "sha256:{{ nomad_consul_cni_checksum_url }}"
    timeout: "42"
  become: false
  tags: installation

- name: Create Temporary Directory for Extraction
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible-nomad.
  become: false
  register: install_temp
  tags: installation
  delegate_to: 127.0.0.1

- name: Unarchive Nomad CNI
  ansible.builtin.unarchive:
    src: "{{ role_path }}/files/{{ nomad_cni_pkg }}"
    dest: "{{ install_temp.path }}/"
    creates: "{{ install_temp.path }}/bridge"
  become: false
  tags: installation
  delegate_to: 127.0.0.1

- name: Unarchive Nomad Consul CNI
  ansible.builtin.unarchive:
    src: "{{ role_path }}/files/{{ nomad_consul_cni_pkg }}"
    dest: "{{ install_temp.path }}/"
    creates: "{{ install_temp.path }}/consul-cni"
  become: false
  tags: installation
  delegate_to: 127.0.0.1

- name: Install Nomad CNI
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nomad_cni_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0755"
  with_fileglob:
    - "{{ install_temp.path }}/*"
  tags: installation
  notify: Restart nomad

- name: Cleanup
  ansible.builtin.file:
    path: "{{ install_temp.path }}"
    state: absent
  become: false
  tags: installation
  delegate_to: 127.0.0.1
